# Generated by Django 4.2.3 on 2024-05-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='event_id',
            field=models.IntegerField(),
        ),
    ]
