# Generated by Django 4.2.3 on 2024-05-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_apikey_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='event_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
